import {
  LeftOutlined,
  RightOutlined,
  LaptopOutlined,
  NotificationOutlined,
  UserOutlined,
  PieChartOutlined,
  TeamOutlined,
  DesktopOutlined,
  FileOutlined,
  ShoppingCartOutlined,
  WarningOutlined,
  ProductOutlined,
  PercentageOutlined,
  DropboxOutlined,
  UsergroupAddOutlined,
  SettingOutlined,
  LogoutOutlined,
  FilterOutlined,
  EditOutlined,
  EyeOutlined,
  PlusOutlined,
} from "@ant-design/icons";

export const icons = {
  RightOutlined,
  LeftOutlined,
  LaptopOutlined,
  NotificationOutlined,
  PieChartOutlined,
  DesktopOutlined,
  UserOutlined,
  TeamOutlined,
  FileOutlined,
  ShoppingCartOutlined,
  WarningOutlined,
  ProductOutlined,
  PercentageOutlined,
  DropboxOutlined,
  UsergroupAddOutlined,
  SettingOutlined,
  LogoutOutlined,
  FilterOutlined,
  EditOutlined,
  EyeOutlined,
  PlusOutlined,
};
